name: Environment-Variables

on:
  push:
    branches:
      - main

env: 
  WF_LEVEL_ENV: This is Workflow level ENV

jobs:
  env-and-contexts:
    runs-on: build-server
    env:
      JOB_LEVEL_ENV: This is Job level ENV
    steps:
      - name: Log ENV VAR
        run: echo $GITHUB_REF
      - name: Log context
        run: echo '${{ github.ref }}'
      - name: Log custom env vars
        env:
          STEP_LEVEL_ENV: This is step level ENV
          WF_LEVEL_ENV: This is overriden in step
        run: |
          echo '${{ env.WF_LEVEL_ENV }}'
          echo $WF_LEVEL_ENV      
          echo $JOB_LEVEL_ENV
          echo $STEP_LEVEL_ENV     
