name: Build and deploy React App

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: build-server 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Node.js version
        run: |
          node -v
          npm -v
        