name: Manual-trigger

on:
  workflow_dispatch:
    inputs:
      string:
        description: "A string input"
        type: string
        default: "set a no"

jobs:
  manual_trigger:
    runs-on: build-server

    steps: 
      - run: echo $GITHUB_SHA
      