name: reusable_workflow
on:
  workflow_call:
    inputs:
      name:
        description: "input"
        type: string
        default: "Farooq"
        required: false

jobs:
   checkout:
     runs-on: ubuntu
     steps:
     - name: checkout
       uses: actions/checkout@v3
       run: ls -a   

    log-context-and-inputs: 
      runs-on: ubuntu
      steps:
      - name: Display content
        run: echo '{{ toJSON(github) }}'        
      - name: Display name
        run: echo {{ inputs.name }}  